### ISSUE TITLE
Structure: 底盘电机数量

### ISSUE THREAD

**Issue by FlyGoat** [GavinYou082/VEX-Robotics2018#10]
根据不同的分配方法，底盘上可以有6个或8个电机，如何选择电机数量？

6个：剩余6个，两个用于取球，取球与存球分开控制，两个弹射，一个翘臂，剩余一个后期应变。

8个：剩余4个，取球一个，两个弹射，一个翘臂。

**Comment by FlyGoat** [comment]
暂时选定6个方案。底盘电机全部使用High Speed齿轮组。

**Comment by gaviny82** [comment]
确定使用8个电机， 另外两个Turbo等待安装
