### ISSUE TITLE
手动程序：一键控制铁拳

### ISSUE THREAD

**Issue by gaviny82** [GavinYou082/VEX-Robotics2018#22]
当按下5U时，自动挑下高杆的盘子并归位
当按下5D时，自动翻地面上的盘子并归为

**Comment by FlyGoat** [comment]
We need an analog sensor to get the degree value. Or it's impossible to reset.
And should we use PID or just make a simple algorithm?

**Comment by gaviny82** [comment]
Default position of the shooting arm should be -22 degrees (measured by mobile phone)

**Comment by gaviny82** [comment]
一键弹射通过测试
